source "https://rubygems.org"

ruby "3.0.6"


gem "rails", "~> 7.1.3", ">= 7.1.3.2"




gem "pg", "~> 1.1"

gem 'rswag'


gem "puma", ">= 5.0"
gem "faker"

gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]


gem "bootsnap", require: false

gem 'rack-cors'

group :development, :test do

  gem 'rspec-rails', ' ~> 6.1.0'

  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ]
end

group :development do
  
end

